
services:
  - type: web
    name: gaza-news-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    autoDeploy: true
    repo: https://github.com/MohammedHosam2008/gaza-news-bot
